### ISSUE TITLE
Immuni e un'implementazione libera delle Exposure Notification API

### ISSUE THREAD

**Issue by Stypox** [dagoneye/civichackingit#1]
Buongiorno, 
come ben saprete è stata sviluppata l'app Immuni, che come tutte le altre app di contact tracing usa le Exposure Notification API. Sebbene il protocollo sia aperto, al momento le uniche implementazioni (Google, Apple e presto Huawei) sono closed-source, quindi per poter usare l'app su Android servono i Google Play Services. Questi ultimi sono disponibili solo su una parte dei dispositivi: ad esempio gli utenti Amazon, gli utenti di Android versione < 6.0, gli utenti di ROM custom senza Google Play Services. Sulla repo github dell'app tedesca è quindi nata una discussione (corona-warn-app/cwa-app-android#75) che si è risolta nella creazione di un implementazione libera del protocollo e dell'app di contact tracing: CoreLibre ( https://github.com/CoraLibre). Essendo però questo un progetto FOSS della community, ci sono difficoltà nella realizzazione date dal piccolo numero di contribuenti. Scrivo quindi per farvi conoscere questa iniziativa: magari qualcuno potrebbe essere interessato a contribuire o a farla conoscere ad altri programmatori in grado di aiutare. 
Grazie per l'attenzione 

P.S. ho provato ad usare la form sul sito ( https://civichacking.it/#contact) ma dice che la mail (non la mia credo, bensì la vostra) non è verificata. Ho quindi scritto qui non sapendo in quale altro modo contattarvi.

**Comment by dagoneye** [comment]
Ciao,
grazie di avermi fatto scoprire che c'era un problema sulla form del sito: ho aggiornato l'associazione con l'indirizzo email, lo avevamo cambiato senza rifare la validazione.  
Per il resto, grazie del ping: il tema è importante e particolarmente complesso, farlo girare di certo aiuta a farlo conoscere.
